### ISSUE TITLE
Gözatın! link hatası

### ISSUE THREAD

**Issue by harslannet** [tayfunerbilen/prototurk.com#3]
ilk olarak sanırım gözünden kaçan küçük bir hatayı bildireyim :) 
"Şu an için neler olup bittiğine siteden gözatın! https://prototurk.com" metninde yer alan prototurk linki "https://github.com/tayfunerbilen/prototurk.com/blob/master" şu adrese gönderiyor 👍

**Comment by tayfunerbilen** [comment]
Teşekkürler, düzeltildi.
